### ISSUE TITLE
Use appropriate numpy/scipy functions if available

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/stardis#17]
Specifically we should not write our own function if Faddeeva or Voigt are available

**Comment by smithis7** [comment]
scipy does have a `voigt_profile()` function (https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.voigt_profile.html) but we tried it and it is not compatible with numba. Perhaps there is a way to make it compatible, or using that function instead of numba on that part of the code could be faster. This will be a good thing for our GSoC student to look at.

**Comment by zafar-hussain** [comment]
Hi @smithis7 , @wkerzendorf 

I just finished a fully vectorized  version of faddeeva function,  as a part of GSOC proposal.

Here is the notebook with the code and timing comparison. 

https://colab.research.google.com/drive/11HGzIw2Q_GhTRNMKleQGUUdUWQQSrGZs?usp=sharing

Please have a look and advise

cheers



I

**Comment by zafar-hussain** [comment]
Hi @smithis7 , @wkerzendorf 

I had a look at the wofz (faddeeva) function in scipy, It is already using cxx code and gets compiled by cython. Hence normal  numba cant compile it further.

There is a project by anaconda called numba scipy, but currently it dose not offer wofz (faddeeva) function.

Secondly the scipy version of faddeeva function uses a slightly   different mechanism, and the values vary from the current implementation by a tolerance of 0.1.

my vector and parallel version give the same values as current implementation.

vector version is slightly slower then scipy version, but the parallel version is twice as fast, on a multi core machine


cheers
